DROP TABLE IF EXISTS brevets;

CREATE TABLE IF NOT EXISTS brevets (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
link_map VARCHAR(255) NOT NULL,
data_year INTEGER NOT NULL,
start_time VARCHAR(255) NOT NULL,
start_place VARCHAR(255) NOT NULL,
cp1_time VARCHAR(255) NOT NULL,
cp1_place VARCHAR(255) NOT NULL,
cp2_time VARCHAR(255) NOT NULL,
cp2_place VARCHAR(255) NOT NULL,
cp3_time VARCHAR(255) NOT NULL,
cp3_place VARCHAR(255) NOT NULL,
cp4_time VARCHAR(255) NOT NULL,
cp4_place VARCHAR(255) NOT NULL,
cp5_time VARCHAR(255) NOT NULL,
cp5_place VARCHAR(255) NOT NULL,
cp6_time VARCHAR(255) NOT NULL,
cp6_place VARCHAR(255) NOT NULL,
cp7_time VARCHAR(255) NOT NULL,
cp7_place VARCHAR(255) NOT NULL,
cp8_time VARCHAR(255) NOT NULL,
cp8_place VARCHAR(255) NOT NULL,
finish_time VARCHAR(255) NOT NULL,
finish_place VARCHAR(255) NOT NULL,

);

DROP TABLE IF EXISTS randonneurs_time_2017;

CREATE TABLE IF NOT EXISTS randonneurs_time_2017 (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
year INTEGER NOT NULL,
time_200 VARCHAR(255) NOT NULL,
time_300 VARCHAR(255) NOT NULL,
time_400 VARCHAR(255) NOT NULL,
time_600 VARCHAR(255) NOT NULL,
);

