DROP TABLE IF EXISTS brevets;

CREATE TABLE IF NOT EXISTS brevets {
id_brevet INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL
}

DROP TABLE IF EXISTS brevet_200_may_2017;

CREATE TABLE IF NOT EXISTS brevet_200_may_2017 {
id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
sex TEXT NOT NULL,
time TEXT NOT NULL
}