DROP TABLE IF EXISTS brevets;

CREATE TABLE IF NOT EXISTS brevets (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
link_map VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS randonneurs_time_2017;

CREATE TABLE IF NOT EXISTS randonneurs_time_2017 (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
year INTEGER NOT NULL,
time_200 VARCHAR(255) NOT NULL,
time_300 VARCHAR(255) NOT NULL,
time_400 VARCHAR(255) NOT NULL,
time_600 VARCHAR(255) NOT NULL,
);

